// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdRYVSRui0M9BKu_WtIa_Lwb0QF-d6oU',
    appId: '1:139196646455:android:f9868438956f5c151a6bb2',
    messagingSenderId: '139196646455',
    projectId: 'g4a4-app',
    storageBucket: 'g4a4-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Ad1NzjD5N6-VZSAtZwWHsyENTEJJ_fM',
    appId: '1:139196646455:ios:321b4b461cda970b1a6bb2',
    messagingSenderId: '139196646455',
    projectId: 'g4a4-app',
    storageBucket: 'g4a4-app.firebasestorage.app',
    iosBundleId: 'com.g4a4.item4gamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFfeR9Za0nss7L86swvLsMsHATZVK6-Q8',
    appId: '1:139196646455:web:735bb02fe76855501a6bb2',
    messagingSenderId: '139196646455',
    projectId: 'g4a4-app',
    authDomain: 'g4a4-app.firebaseapp.com',
    storageBucket: 'g4a4-app.firebasestorage.app',
  );

}